version: '3.8'

services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # Usamos --reload para desenvolvimento
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    # Comando para iniciar o worker Celery
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - redis
  
  redis:
    image: "redis:7-alpine" # Usamos uma versão específica para consistência