# render.yaml (Versão Corrigida e Profissional)
# Descreve a infraestrutura usando os tipos de serviço geridos do Render.

services:
  # 1. O nosso Banco de Dados PostgreSQL Gerido
  - name: cortex-create-db
    type: postgres # CORREÇÃO: Usamos o tipo dedicado 'postgres'
    postgresMajorVersion: 14 # Especificamos a versão desejada
    plan: free

  # 2. O nosso Message Broker Redis Gerido
  - name: cortex-create-redis
    type: redis # CORREÇÃO: Usamos o tipo dedicado 'redis'
    redisVersion: 7 # Especificamos a versão desejada
    plan: free

  # 3. O nosso Backend (API FastAPI)
  - name: cortex-create-api
    type: web
    env: docker
    
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres # CORREÇÃO: Apontamos para o tipo correto
          name: cortex-create-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis # CORREÇÃO: Apontamos para o tipo correto
          name: cortex-create-redis
          property: connectionString
      - key: REPLICATE_API_TOKEN
        sync: false # Mantemos esta configuração para a chave secreta

  # 4. O nosso Worker (Celery)
  - name: cortex-create-worker
    type: worker
    env: docker
    startCommand: celery -A app.worker.celery_app worker --loglevel=info
    
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres # CORREÇÃO: Apontamos para o tipo correto
          name: cortex-create-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis # CORREÇÃO: Apontamos para o tipo correto
          name: cortex-create-redis
          property: connectionString
      - key: REPLICATE_API_TOKEN
        sync: false