# render.yaml (Teste Mínimo de Isolamento)

services:
  - name: cortex-create-api-test
    type: web
    env: docker
    # Nota: Removemos todas as envVars por agora.
    # O build irá passar, mas a aplicação irá falhar ao iniciar, o que é esperado.